# Generated by Django 4.0.4 on 2022-06-04 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actor', '0003_alter_actor_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='gender',
            field=models.CharField(choices=[('m', 'Male'), ('f', 'Female')], default='m', max_length=1),
        ),
    ]
