# Generated by Django 4.0.4 on 2022-06-05 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actor', '0004_alter_actor_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='age',
        ),
        migrations.RemoveField(
            model_name='actor',
            name='nationality',
        ),
        migrations.AddField(
            model_name='actor',
            name='profile_img',
            field=models.ImageField(null=b'I01\n', upload_to='actor'),
            preserve_default=b'I01\n',
        ),
    ]
