# Generated by Django 4.0.4 on 2022-06-05 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actor', '0005_remove_actor_age_remove_actor_nationality_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='profile_img',
            field=models.ImageField(default='Screenshot from 2022-06-03 18-53-16.png', upload_to='actor'),
        ),
    ]
